### ISSUE TITLE
Enable serviceusage.googleapis.com?

### ISSUE THREAD

**Issue by mrtyler** [exekube/exekube#90]
I have an [exekube project](https://github.com/gpii-ops/gpii-infra/tree/master/gcp). It's pretty straightforward for now, basically a copy of https://github.com/exekube/demo-apps-project/.

EDIT: I am using exekube:0.3.1-google with some trivial changes.

When I create the cluster for the first time (`xk gcp-project-init; xk up live/dev/infra`), I get this error (once per API terraform tries to enable):
```
* google_project_service.services.0: Error enabling service:
Error enabling service ["compute.googleapis.com"] for project "xk-tyler11":
googleapi: Error 403: Service Usage API has not been used in project 602744036260
before or it is disabled.
Enable it by visiting
https://console.developers.google.com/apis/api/serviceusage.googleapis.com/overview?project=602744036260
then retry.
If you enabled this API recently, wait a few minutes for the action to propagate to our systems
and retry.
, accessNotConfigured
```

I tried adding `serviceusage.googleapis.com` to `${var.project_services}` [here](https://github.com/exekube/exekube/blob/master/modules/gke-network/variables.tf#L5), but it didn't help.

I can fix it by running:
```
$ xk gcloud services enable serviceusage.googleapis.com
```

(and then waiting a couple minutes).

Shall I add this step to `gcp-project-init`? Or is there a better way to solve this?

**Comment by ilyasotkov** [comment]
We can definitely add this to the `gcp-project-init` script if that quickly solves the problem.

**Comment by ilyasotkov** [comment]
Clone by https://github.com/exekube/exekube/pull/93.
